<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 2</b></center>    
<pre>



### Step 1. Import the necessary libraries

In [4]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|")
df

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 4. See the first 25 entries

In [10]:
df.head(25)

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

### Step 5. See the last 10 entries

In [11]:
df.tail(25)

     user_id  age gender     occupation zip_code
918      919   25      M          other    14216
919      920   30      F         artist    90008
920      921   20      F        student    98801
921      922   29      F  administrator    21114
922      923   21      M        student    E2E3R
923      924   29      M          other    11753
924      925   18      F       salesman    49036
925      926   49      M  entertainment    01701
926      927   23      M     programmer    55428
927      928   21      M        student    55408
928      929   44      M      scientist    53711
929      930   28      F      scientist    07310
930      931   60      M       educator    33556
931      932   58      M       educator    06437
932      933   28      M        student    48105
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [12]:
df.shape

(943, 5)

### Step 7. What is the number of columns in the dataset?

In [13]:
df.shape[1]

5

### Step 8. Print the name of all the columns.

In [14]:
df.columns

Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [15]:
df.index

RangeIndex(start=0, stop=943, step=1)

### Step 10. What is the data type of each column?

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB

### Step 11. Print only the occupation column

In [17]:
df['occupation']
df[['occupation','age']]

        occupation  age
0       technician   24
1            other   53
2           writer   23
3       technician   24
4            other   33
..             ...  ...
938        student   26
939  administrator   32
940        student   20
941      librarian   48
942        student   22

[943 rows x 2 columns]

### Step 12. How many different occupations are in this dataset?

In [18]:
df['occupation'].unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

### Step 13. What is the most frequent occupation?

In [19]:
df['occupation'].value_counts().head()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

In [20]:
df.describe()

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

### Step 15. Summarize all the columns

In [21]:
# df.describe(include="all")
df.describe(include="object")

       gender occupation zip_code
count     943        943      943
unique      2         21      795
top         M    student    55414
freq      670        196        9

### Step 16. Summarize only the occupation column

In [22]:
# df["occupation"].describe(include="object")
df['age'].describe()

count    943.000000
mean      34.051962
std       12.192740
min        7.000000
25%       25.000000
50%       31.000000
75%       43.000000
max       73.000000
Name: age, dtype: float64

### Step 17. What is the mean age of users?

In [23]:
df['age'].mean()
df

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 18. What is the age with least occurrence?

In [24]:
df['age'].value_counts().tail(1)

age
73    1
Name: count, dtype: int64

## Part -2

- **All tasks** are based on the **single dataset** loaded in the Setup cell below.

In [25]:
import pandas as pd
import numpy as np

np.random.seed(42)
n = 200

cities    = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix',
             'Philadelphia', 'San Antonio', 'Dallas', 'Austin', 'Seattle']
regions   = {'New York': 'East', 'Los Angeles': 'West', 'Chicago': 'North',
             'Houston': 'South', 'Phoenix': 'West', 'Philadelphia': 'East',
             'San Antonio': 'South', 'Dallas': 'South', 'Austin': 'South', 'Seattle': 'West'}
categories = ['Electronics', 'Clothing', 'Food', 'Furniture']
products   = {
    'Electronics': ['Laptop', 'Smartphone', 'Headphones', 'Tablet', 'Camera'],
    'Clothing':    ['T-Shirt', 'Jeans', 'Jacket', 'Sneakers', 'Dress'],
    'Food':        ['Coffee Beans', 'Olive Oil', 'Pasta', 'Chocolate', 'Tea'],
    'Furniture':   ['Office Chair', 'Desk', 'Bookshelf', 'Sofa', 'Lamp']
}
prices     = {
    'Laptop': 999.99, 'Smartphone': 799.99, 'Headphones': 199.99,
    'Tablet': 499.99, 'Camera': 649.99, 'T-Shirt': 29.99,
    'Jeans': 59.99, 'Jacket': 89.99, 'Sneakers': 79.99, 'Dress': 69.99,
    'Coffee Beans': 14.99, 'Olive Oil': 12.99, 'Pasta': 5.99,
    'Chocolate': 8.99, 'Tea': 9.99, 'Office Chair': 249.99,
    'Desk': 349.99, 'Bookshelf': 149.99, 'Sofa': 799.99, 'Lamp': 49.99
}
salespersons = ['Alice Johnson', 'Bob Martinez', 'Carol White',
                'David Lee', 'Emma Davis']
first_names  = ['James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer',
                'Michael', 'Linda', 'William', 'Barbara', 'David', 'Susan',
                'Richard', 'Jessica', 'Thomas', 'Sarah', 'Charles', 'Karen',
                'Daniel', 'Lisa']
last_names   = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia',
                'Miller', 'Davis', 'Wilson', 'Moore', 'Taylor', 'Anderson',
                'Thomas', 'Jackson', 'White', 'Harris', 'Martin', 'Thompson',
                'Young', 'Robinson']

city_list    = np.random.choice(cities, n)
cat_list     = np.random.choice(categories, n)
prod_list    = [np.random.choice(products[c]) for c in cat_list]
price_list   = np.array([prices[p] for p in prod_list])
disc_list    = np.random.choice([0, 5, 10, 15, 20, 25, 30], n)
qty_list     = np.random.randint(1, 11, n)
rating_list  = np.random.choice([1, 2, 3, 4, 5], n, p=[0.05, 0.10, 0.20, 0.40, 0.25])
dates        = pd.date_range(start='2023-01-01', end='2023-12-31', periods=n)
dates        = pd.to_datetime(np.sort(np.random.choice(dates, n, replace=False)))
cust_names   = [f"{np.random.choice(first_names)} {np.random.choice(last_names)}" for _ in range(n)]

# Introduce some missing values
rating_arr = rating_list.astype(float)
rating_arr[np.random.choice(n, 12, replace=False)] = np.nan
disc_arr = disc_list.astype(float)
disc_arr[np.random.choice(n, 8, replace=False)] = np.nan

df = pd.DataFrame({
    'order_id':      [f'ORD-{1000+i}' for i in range(n)],
    'order_date':    dates,
    'customer_name': cust_names,
    'city':          city_list,
    'region':        [regions[c] for c in city_list],
    'category':      cat_list,
    'product':       prod_list,
    'quantity':      qty_list,
    'unit_price':    price_list,
    'discount':      disc_arr,
    'salesperson':   np.random.choice(salespersons, n),
    'rating':        rating_arr
})

# Add duplicate rows intentionally
df = pd.concat([df, df.iloc[[5, 23, 77]]], ignore_index=True)


df.head()

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
0,ORD-1000,2023-01-01 00:00:00.000000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0
1,ORD-1001,2023-01-02 19:53:58.190954773,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0
2,ORD-1002,2023-01-04 15:47:56.381909547,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,NaN
3,ORD-1003,2023-01-06 11:41:54.572864321,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0
4,ORD-1004,2023-01-08 07:35:52.763819095,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0

### ✅ Task 1 — First Inspection
Perform a basic inspection of the DataFrame `df`:
1. Display the **first 8 rows**.
2. Display the **last 5 rows**.
3. Print the **shape** (rows, columns).
4. Print all **column names**.

In [26]:
df.head(8)

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
0,ORD-1000,2023-01-01 00:00:00.000000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0
1,ORD-1001,2023-01-02 19:53:58.190954773,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0
2,ORD-1002,2023-01-04 15:47:56.381909547,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,NaN
3,ORD-1003,2023-01-06 11:41:54.572864321,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0
4,ORD-1004,2023-01-08 07:35:52.763819095,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0
5,ORD-1005,2023-01-10 03:29:50.954773869,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0
6,ORD-1006,2023-01-11 23:23:49.145728643,Mary Williams,Chicago,North,Electronics,Laptop,5,999.99,15.0,Emma Davis,NaN
7,ORD-1007,2023-01-13 19:17:47.336683417,Robert Taylor,San Antonio,South,Furniture,Bookshelf,6,149.99,20.0,Alice Johnson,5.0

In [27]:
df.tail()

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
198,ORD-1198,2023-12-29 04:06:01.809045228,Robert Brown,Los Angeles,West,Food,Tea,4,9.99,0.0,Alice Johnson,4.0
199,ORD-1199,2023-12-31 00:00:00.000000000,Susan Robinson,Philadelphia,East,Clothing,Dress,6,69.99,10.0,Bob Martinez,NaN
200,ORD-1005,2023-01-10 03:29:50.954773869,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0
201,ORD-1023,2023-02-12 01:41:18.391959799,Michael Robinson,Philadelphia,East,Furniture,Bookshelf,1,149.99,10.0,Emma Davis,NaN
202,ORD-1077,2023-05-21 20:15:40.703517588,Sarah Davis,Austin,South,Food,Tea,2,9.99,5.0,Bob Martinez,4.0

In [28]:
df.shape

(203, 12)

In [29]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'city', 'region', 'category',
       'product', 'quantity', 'unit_price', 'discount', 'salesperson',
       'rating'],
      dtype='object')

### ✅ Task 2 — Data Types & Info
1. Display the **data type** of each column using `.dtypes`.
2. Use `.info()` to get a full summary.
3. Identify which columns have **missing values** and how many.

In [30]:
df.dtypes

order_id                 object
order_date       datetime64[ns]
customer_name            object
city                     object
region                   object
category                 object
product                  object
quantity                  int32
unit_price              float64
discount                float64
salesperson              object
rating                  float64
dtype: object

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       203 non-null    object
 1   order_date     203 non-null    datetime64[ns]
 2   customer_name  203 non-null    object
 3   city           203 non-null    object
 4   region         203 non-null    object
 5   category       203 non-null    object
 6   product        203 non-null    object
 7   quantity       203 non-null    int32
 8   unit_price     203 non-null    float64
 9   discount       195 non-null    float64
 10  salesperson    203 non-null    object
 11  rating         190 non-null    float64
dtypes: datetime64[ns](1), float64(3), int32(1), object(7)
memory usage: 18.4+ KB

In [32]:
df.isnull().sum()

order_id          0
order_date        0
customer_name     0
city              0
region            0
category          0
product           0
quantity          0
unit_price        0
discount          8
salesperson       0
rating           13
dtype: int64

### ✅ Task 3 — Descriptive Statistics
1. Use `.describe()` to get summary statistics for **all numeric columns**.
2. Use `.describe(include='object')` to get statistics for **text columns**.
3. Print the **mean**, **min**, and **max** of `unit_price` separately.

In [33]:
df.describe()

,order_date,quantity,unit_price,discount,rating
count,203,203.000000,203.0000,195.000000,190.000000
mean,2023-06-30 06:09:17.684976640,5.389163,274.1033,14.692308,3.810526
min,2023-01-01 00:00:00,1.000000,5.9900,0.000000,1.000000
25%,2023-03-30 17:07:32.261306368,3.000000,29.9900,5.000000,3.000000
50%,2023-06-29 06:09:02.713567744,5.000000,89.9900,15.000000,4.000000
75%,2023-09-29 15:04:31.356783872,8.000000,424.9900,20.000000,5.000000
max,2023-12-31 00:00:00,10.000000,999.9900,30.000000,5.000000
std,NaN,2.875516,315.2740,9.826206,1.021408

In [34]:
df.describe(include='object')

,order_id,customer_name,city,region,category,product,salesperson
count,203,203,203,203,203,203,203
unique,200,152,10,4,4,20,5
top,ORD-1005,Jessica White,San Antonio,South,Furniture,Desk,Emma Davis
freq,2,4,26,88,67,17,50

In [35]:
print(f"mean= {df['unit_price'].mean()}")
print(f"min= {df['unit_price'].min()}")
print(f"max= {df['unit_price'].max()}")

mean= 274.1033004926108
min= 5.99
max= 999.99

### ✅ Task 4 — Selecting Columns
1. Select and display only the `customer_name` and `city` columns.
2. Select the columns `product`, `quantity`, `unit_price` and display the **first 10 rows**.
3. Store the `unit_price` column as a **Pandas Series** named `prices_series` and print its type.

In [36]:
df[['customer_name','city']]

        customer_name          city
0      Karen Robinson   San Antonio
1    Michael Williams       Houston
2         Karen Moore        Dallas
3      Michael Martin       Phoenix
4    Jessica Williams   San Antonio
..                ...           ...
198      Robert Brown   Los Angeles
199    Susan Robinson  Philadelphia
200      Susan Thomas       Seattle
201  Michael Robinson  Philadelphia
202       Sarah Davis        Austin

[203 rows x 2 columns]

In [37]:
df[['product','quantity','unit_price']].head(10)

        product  quantity  unit_price
0        Jacket         1       89.99
1     Olive Oil         5       12.99
2     Olive Oil         7       12.99
3          Desk         6      349.99
4  Office Chair         1      249.99
5        Laptop         5      999.99
6        Laptop         5      999.99
7     Bookshelf         6      149.99
8           Tea         3        9.99
9         Jeans         5       59.99

In [38]:
pandas_series = df['unit_price']
print(type(pandas_series))

<class 'pandas.core.series.Series'>

### ✅ Task 5 — Filtering Rows
Filter and display:
1. All orders from the **'Electronics'** category.
2. All orders where `quantity` is **greater than 7**.
3. All orders from **'New York'** city.
4. Print the **row count** for each filtered result.

In [39]:
ele = df[df['category']=='Electronics']

In [40]:
qua = df[df['quantity']>7]

In [41]:
new = df[df['city']=='New York']

In [42]:
print(f"electronics orders row count: {ele.shape[0]}")
print(f"quantity>7 row count: {qua.shape[0]}")
print(f"New York city row count: {new.shape[0]}")

electronics orders row count: 48
quantity>7 row count: 57
New York city row count: 23

### ✅ Task 6 — Sorting
1. Sort the DataFrame by `unit_price` in **descending order** and display the top 10 rows.
2. Sort by `category` (ascending) and then by `unit_price` (descending) — **multi-column sort**.
3. Display the **cheapest 5 products** (by unit_price).

In [43]:
s = df.sort_values(by = 'unit_price', ascending=False)
print(s.head(10))

     order_id                    order_date    customer_name         city  \
6    ORD-1006 2023-01-11 23:23:49.145728643    Mary Williams      Chicago
5    ORD-1005 2023-01-10 03:29:50.954773869     Susan Thomas      Seattle
33   ORD-1033 2023-03-02 08:41:00.301507538      Susan Jones      Chicago
74   ORD-1074 2023-05-16 08:33:46.130653266     Linda Thomas       Dallas
63   ORD-1063 2023-04-26 05:40:06.030150754    David Johnson      Seattle
180  ORD-1180 2023-11-26 05:54:34.371859296  Patricia Garcia  San Antonio
176  ORD-1176 2023-11-18 22:18:41.608040200   Linda Thompson     New York
167  ORD-1167 2023-11-02 11:12:57.889447236      Karen White      Houston
200  ORD-1005 2023-01-10 03:29:50.954773869     Susan Thomas      Seattle
107  ORD-1107 2023-07-15 17:14:46.432160804      Susan Brown       Dallas

    region     category product  quantity  unit_price  discount  \
6    North  Electronics  Laptop         5      999.99      15.0
5     West  Electronics  Laptop         5      999.99      20.0
33   North  Electronics  Laptop         6      999.99      20.0
74   South  Electronics  Laptop         2      999.99      10.0
63    West  Electronics  Laptop         1      999.99      10.0
180  South  Electronics  Laptop         5      999.99       0.0
176   East  Electronics  Laptop         9      999.99      10.0
167  South  Electronics  Laptop         9      999.99       5.0
200   West  Electronics  Laptop         5      999.99      20.0
107  South  Electronics  Laptop         1      999.99      20.0

       salesperson  rating
6       Emma Davis     NaN
5       Emma Davis     4.0
33   Alice Johnson     5.0
74    Bob Martinez     NaN
63     Carol White     4.0
180   Bob Martinez     4.0
176      David Lee     4.0
167     Emma Davis     3.0
200     Emma Davis     4.0
107    Carol White     4.0

In [44]:
s = df.sort_values(by = ['category','unit_price'], ascending=[True,False])
print(s)

     order_id                    order_date    customer_name          city  \
0    ORD-1000 2023-01-01 00:00:00.000000000   Karen Robinson   San Antonio
56   ORD-1056 2023-04-13 10:22:18.693467337   Robert Johnson   Los Angeles
81   ORD-1081 2023-05-29 03:51:33.467336684    Barbara Brown        Austin
124  ORD-1124 2023-08-15 19:32:15.678391960      Sarah Jones      New York
127  ORD-1127 2023-08-21 07:14:10.251256284       John Smith       Phoenix
..        ...                           ...              ...           ...
109  ORD-1109 2023-07-19 09:02:42.814070352     Susan Miller       Chicago
152  ORD-1152 2023-10-06 00:43:25.025125628  Jennifer Wilson  Philadelphia
154  ORD-1154 2023-10-09 16:31:21.407035176    Daniel Wilson        Austin
172  ORD-1172 2023-11-11 14:42:48.844221108   William Garcia       Phoenix
183  ORD-1183 2023-12-01 17:36:28.944723620   David Thompson      New York

    region   category product  quantity  unit_price  discount    salesperson  \
0    South   Clothing  Jacket         1       89.99      10.0      David Lee
56    West   Clothing  Jacket         9       89.99       0.0      David Lee
81   South   Clothing  Jacket         7       89.99      15.0      David Lee
124   East   Clothing  Jacket         6       89.99      30.0    Carol White
127   West   Clothing  Jacket         8       89.99      25.0      David Lee
..     ...        ...     ...       ...         ...       ...            ...
109  North  Furniture    Lamp         9       49.99      20.0      David Lee
152   East  Furniture    Lamp         4       49.99      25.0    Carol White
154  South  Furniture    Lamp         4       49.99       0.0     Emma Davis
172   West  Furniture    Lamp         2       49.99       5.0  Alice Johnson
183   East  Furniture    Lamp         7       49.99       5.0   Bob Martinez

     rating
0       5.0
56      4.0
81      4.0
124     2.0
127     5.0
..      ...
109     4.0
152     3.0
154     3.0
172     5.0
183     4.0

[203 rows x 12 columns]

In [45]:
s = df.sort_values(by = 'unit_price', ascending=True)
print(s.head(5))

     order_id                    order_date     customer_name         city  \
123  ORD-1123 2023-08-13 23:38:17.487437188       Susan White  San Antonio
114  ORD-1114 2023-07-28 12:32:33.768844220   Jessica Johnson     New York
196  ORD-1196 2023-12-25 12:18:05.427135680  Michael Anderson      Phoenix
140  ORD-1140 2023-09-14 01:55:46.733668344    Thomas Jackson      Seattle
43   ORD-1043 2023-03-20 15:40:42.211055277       Mary Wilson       Austin

    region category    product  quantity  unit_price  discount    salesperson  \
123  South     Food      Pasta         8        5.99      30.0  Alice Johnson
114   East     Food      Pasta         8        5.99      10.0   Bob Martinez
196   West     Food      Pasta         2        5.99       0.0  Alice Johnson
140   West     Food      Pasta         9        5.99      15.0      David Lee
43   South     Food  Chocolate         5        8.99       5.0  Alice Johnson

     rating
123     2.0
114     4.0
196     5.0
140     5.0
43      4.0

### ✅ Task 7 — Value Counts
1. Count how many orders belong to each **category**.
2. Count how many orders were handled by each **salesperson**.
3. Find the **most common city** in the dataset.
4. Show the distribution of **customer ratings** (including NaN count).

In [46]:
df['category'].value_counts()

category
Furniture      67
Electronics    48
Food           47
Clothing       41
Name: count, dtype: int64

In [47]:
df['salesperson'].value_counts()

salesperson
Emma Davis       50
David Lee        48
Bob Martinez     41
Alice Johnson    36
Carol White      28
Name: count, dtype: int64

In [48]:
# df['city'].value_counts().idxmax()
s=df.value_counts().sort_values(by='city',ascending=False).head(1)
s

TypeError: Series.sort_values() got an unexpected keyword argument 'by'

In [49]:
df['rating'].value_counts(dropna=False)

rating
4.0    85
5.0    49
3.0    33
2.0    17
NaN    13
1.0     6
Name: count, dtype: int64

### ✅ Task 8 — Adding a New Column
Add a new column called **`total_revenue`** computed as:
> `total_revenue = quantity × unit_price × (1 - discount / 100)`

> ⚠️ Treat missing `discount` values as **0** (no discount).

Print the first 10 rows showing `product`, `quantity`, `unit_price`, `discount`, and `total_revenue`.

In [50]:
df['total_revenue'] = df['quantity'] * df['unit_price'] * (1 - df['discount'].fillna(0) / 100)
total_revenue

NameError: name 'total_revenue' is not defined

In [51]:
df[['product','quantity','unit_price','discount','total_revenue']].head(10)

        product  quantity  unit_price  discount  total_revenue
0        Jacket         1       89.99      10.0        80.9910
1     Olive Oil         5       12.99      15.0        55.2075
2     Olive Oil         7       12.99       0.0        90.9300
3          Desk         6      349.99      15.0      1784.9490
4  Office Chair         1      249.99      10.0       224.9910
5        Laptop         5      999.99      20.0      3999.9600
6        Laptop         5      999.99      15.0      4249.9575
7     Bookshelf         6      149.99      20.0       719.9520
8           Tea         3        9.99      30.0        20.9790
9         Jeans         5       59.99       0.0       299.9500

### ✅ Task 9 — Handling Missing Values
1. Count the total number of missing values in the **entire DataFrame**.
2. Fill missing `rating` values with the **median** rating.
3. Fill missing `discount` values with **0**.
4. Confirm there are **no more missing values** after filling.

In [52]:
df.isnull().sum().sum()

np.int64(21)

In [53]:
med = df['rating'].median()
df['rating'] = df['rating'].fillna(med)

In [54]:
df['discount'] = df['discount'].fillna(0)

In [55]:
df.isnull().sum().sum()

np.int64(0)

### ✅ Task 10 — Removing Duplicates
1. Check how many **duplicate rows** exist in the DataFrame.
2. Display the duplicate rows.
3. Remove duplicates and store the clean DataFrame back into `df`.
4. Confirm the new shape.

In [56]:
df.duplicated().sum()

np.int64(3)

In [57]:
df[df.duplicated()]

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating,total_revenue
200,ORD-1005,2023-01-10 03:29:50.954773869,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0,3999.960
201,ORD-1023,2023-02-12 01:41:18.391959799,Michael Robinson,Philadelphia,East,Furniture,Bookshelf,1,149.99,10.0,Emma Davis,4.0,134.991
202,ORD-1077,2023-05-21 20:15:40.703517588,Sarah Davis,Austin,South,Food,Tea,2,9.99,5.0,Bob Martinez,4.0,18.981

In [58]:
print("New Shape: ",df.shape)

New Shape:  (203, 13)

### ✅ Task 11 — Renaming and Dropping Columns
1. Rename the column `unit_price` to `price_usd` and `customer_name` to `customer`.
2. Drop the column `order_id` from a **copy** of the DataFrame (do not modify `df`).
3. Reset the index of that copy and print it.

In [64]:
df = df.rename(columns={
              'unit_price' : 'print_usd',
              'customer_name' : 'customer'})

In [60]:
df_copy = df.drop('order_id',axis=1)

In [61]:

df_copy = df_copy.reset_index(drop=True)

df_copy

,order_date,customer,city,region,category,product,quantity,print_usd,discount,salesperson,rating,total_revenue
0,2023-01-01 00:00:00.000000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0,80.9910
1,2023-01-02 19:53:58.190954773,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0,55.2075
2,2023-01-04 15:47:56.381909547,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,4.0,90.9300
3,2023-01-06 11:41:54.572864321,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0,1784.9490
4,2023-01-08 07:35:52.763819095,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0,224.9910
...,...,...,...,...,...,...,...,...,...,...,...,...
198,2023-12-29 04:06:01.809045228,Robert Brown,Los Angeles,West,Food,Tea,4,9.99,0.0,Alice Johnson,4.0,39.9600
199,2023-12-31 00:00:00.000000000,Susan Robinson,Philadelphia,East,Clothing,Dress,6,69.99,10.0,Bob Martinez,4.0,377.9460
200,2023-01-10 03:29:50.954773869,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0,3999.9600
201,2023-02-12 01:41:18.391959799,Michael Robinson,Philadelphia,East,Furniture,Bookshelf,1,149.99,10.0,Emma Davis,4.0,134.9910
202,2023-05-21 20:15:40.703517588,Sarah Davis,Austin,South,Food,Tea,2,9.99,5.0,Bob Martinez,4.0,18.9810

### ✅ Task 12 — `loc` and `iloc`
Using the original `df`:
1. Use **`iloc`** to select rows 10 to 20 and the first 4 columns.
2. Use **`loc`** to select all rows where `region == 'West'`, showing only `city`, `product`, and `unit_price`.
3. Use **`loc`** to update the `discount` of row at index `0` to `50`.

In [ ]:
df.iloc[10:21, 0:4]

In [65]:
df.loc[df['region'] == 'west', ['city','product','price_usd']]

KeyError: "['price_usd'] not in index"

In [62]:
df.loc[0,'discount']=50
df

,order_id,order_date,customer,city,region,category,product,quantity,print_usd,discount,salesperson,rating,total_revenue
0,ORD-1000,2023-01-01 00:00:00.000000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,50.0,David Lee,5.0,80.9910
1,ORD-1001,2023-01-02 19:53:58.190954773,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0,55.2075
2,ORD-1002,2023-01-04 15:47:56.381909547,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,4.0,90.9300
3,ORD-1003,2023-01-06 11:41:54.572864321,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0,1784.9490
4,ORD-1004,2023-01-08 07:35:52.763819095,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0,224.9910
...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,ORD-1198,2023-12-29 04:06:01.809045228,Robert Brown,Los Angeles,West,Food,Tea,4,9.99,0.0,Alice Johnson,4.0,39.9600
199,ORD-1199,2023-12-31 00:00:00.000000000,Susan Robinson,Philadelphia,East,Clothing,Dress,6,69.99,10.0,Bob Martinez,4.0,377.9460
200,ORD-1005,2023-01-10 03:29:50.954773869,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0,3999.9600
201,ORD-1023,2023-02-12 01:41:18.391959799,Michael Robinson,Philadelphia,East,Furniture,Bookshelf,1,149.99,10.0,Emma Davis,4.0,134.9910
202,ORD-1077,2023-05-21 20:15:40.703517588,Sarah Davis,Austin,South,Food,Tea,2,9.99,5.0,Bob Martinez,4.0,18.9810